name: Delete Package Versions
on:
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v2.0.1
        with:
          package-name: 'com.nishtha.packagesissue2.maven-project'
